<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-MDF97HJ" name="assignments.Assignment_12.Assignment_12" tests="2" failures="1" timestamp="30 Oct 2021 03:39:02 GMT" time="9.141" errors="0">
  <testcase name="uniqueOfficeLocation" time="7.488" classname="assignments.Assignment_12.Assignment_12"/>
  <testcase name="verifyPositionPerEmpCount" time="1.653" classname="assignments.Assignment_12.Assignment_12">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Invalid Employee count for Office Manager position expected [3] but found [1],
	Invalid Employee count for Marketing Designer position expected [2] but found [1],
	Invalid Employee count for Software Engineer position expected [6] but found [2]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	Invalid Employee count for Office Manager position expected [3] but found [1],
	Invalid Employee count for Marketing Designer position expected [2] but found [1],
	Invalid Employee count for Software Engineer position expected [6] but found [2]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at assignments.Assignment_12.Assignment_12.verifyPositionPerEmpCount(Assignment_12.java:382)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- verifyPositionPerEmpCount -->
</testsuite> <!-- assignments.Assignment_12.Assignment_12 -->
